name: Build and Test .NET on Mono

on: [push]  # Trigger the workflow on push events

jobs:
  build_and_test:
    runs-on: ubuntu-latest  # Use a Linux runner with Mono support

    steps:
      - uses: actions/checkout@v3

      - name: Setup Mono
        run: |
          sudo apt-get install -y mono-complete
          sudo apt-get install -y nuget

      - name: Restore dependencies
        run: |
          nuget restore
          nuget install NUnit.ConsoleRunner --version 3.16.3 -o packages

      - name: Build
        run: msbuild maze-gen.sln

      - name: Test
        run: cd build/Debug/tests && ../../../packages/NUnit.ConsoleRunner.3.13.0/tools/nunit3-console tests.dll --where=\"Category!=Load\"  # Replace with your test assembly path
